name: React and API - Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install

  test-api:
    name: API Tests
    runs-on: ubuntu-latest
    - run: npm run test:api

  test-react:
    name: React Tests
    runs-on: ubuntu-latest
    - run: npm run test:react-coverage -- --watchAll=false
