name: React and API - Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install

  test_api:
    name: API Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run test:api

  test_react:
    name: React Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run test:react-coverage -- --watchAll=false
